pipeline {
    agent any
    
    stages {
        stage('Preparation') {
            steps {
                checkout scm
                sh "git rev-parse --short HEAD > .git/commit-id"
            }
        }

        stage('Test') {
            steps {
                script {
                    dir('/app') {
                      echo 'Node';
                      sh 'npm install'
                }
            }
        }

        stage('Deploy Docker Compose') {
            steps {
                script {
                    dir('/app') {
                        echo 'Docker';
                        sh 'docker build -t anuragwebshark/node-demo'
                        sh 'docker run anuragwebshark/node-demo'
                    }
                }
            }
        }
    }
}
