pipeline {
    agent any
    
    stages {
        stage('Preparation') {
            steps {
                checkout scm
                sh "git rev-parse --short HEAD > .git/commit-id"
            }
        }

        stage('Test') {
            steps {
                nodejs(nodeJSInstallationName: 'nodejs') {
                    sh 'npm install'
                }
            }
        }

        stage('Deploy Docker Compose') {
            steps {
                script {
                    dir('/app') {
                        sh 'docker-compose up -d'
                    }
                }
            }
        }
    }
}
