version: '3'

services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - '8080:8080'
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket from host to Jenkins container

  node_app:
    build: ./ #node_app is in app folder inside container
    ports:
      - '3000:3001'

volumes:
  jenkins_home:
