version: '3'

services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - '8080:8080'
    volumes:
      - jenkins_home:/var/jenkins_home

  node_app:
    build: /app #node_app is in app folder inside container
    ports:
      - '3001:3001'

volumes:
  jenkins_home:
